/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Payment Service API
 * Price engine, fee management and SePay payment integration
 * OpenAPI spec version: 1.0.0
 */
export type PostLoginBody = {
  email: string;
  password: string;
};

export type GetStatsParams = {
from?: string;
to?: string;
};

export type PatchCallbackSecretBody = {
  /**
     * New secret (min 32 chars)
     * @minLength 32
     */
  secret: string;
};

export type PatchCallbackSecret200Data = { [key: string]: unknown };

export type PatchCallbackSecret200 = {
  success?: boolean;
  data?: PatchCallbackSecret200Data;
};

export type PostBypassPaymentBody = {
  admin_key: string;
  order_id: number;
};

export type PostBypassSellPaymentBody = {
  admin_key: string;
  order_id: number;
};

export type PostCmsLoginBody = {
  email: string;
  password: string;
};

export type PostCmsLogin200Data = {
  access_token?: string;
  token_type?: string;
  expires_in?: number;
};

export type PostCmsLogin200 = {
  success?: boolean;
  data?: PostCmsLogin200Data;
};

export type PostCmsAdminsBody = {
  /** CMS create-admin key */
  key: string;
  email: string;
  /** @minLength 8 */
  password: string;
};

export type PostCmsAdmins201Data = {
  id?: number;
  email?: string;
};

export type PostCmsAdmins201 = {
  success?: boolean;
  data?: PostCmsAdmins201Data;
};

export type GetCmsConfig200DataConfigsUsdcBuy = {
  spread?: number;
  fee_rate?: number;
  min_fee?: number;
  min_order_amount?: number;
  max_order_amount?: number;
  source?: string;
};

export type GetCmsConfig200DataConfigsUsdcSell = {
  spread?: number;
  fee_rate?: number;
  min_fee?: number;
  min_order_amount?: number;
  max_order_amount?: number;
  source?: string;
};

export type GetCmsConfig200DataConfigsUsdc = {
  buy?: GetCmsConfig200DataConfigsUsdcBuy;
  sell?: GetCmsConfig200DataConfigsUsdcSell;
};

export type GetCmsConfig200DataConfigsXlmBuy = {
  spread?: number;
  fee_rate?: number;
  min_fee?: number;
  min_order_amount?: number;
  max_order_amount?: number;
  source?: string;
};

export type GetCmsConfig200DataConfigsXlmSell = {
  spread?: number;
  fee_rate?: number;
  min_fee?: number;
  min_order_amount?: number;
  max_order_amount?: number;
  source?: string;
};

export type GetCmsConfig200DataConfigsXlm = {
  buy?: GetCmsConfig200DataConfigsXlmBuy;
  sell?: GetCmsConfig200DataConfigsXlmSell;
};

export type GetCmsConfig200DataConfigs = {
  usdc?: GetCmsConfig200DataConfigsUsdc;
  xlm?: GetCmsConfig200DataConfigsXlm;
};

export type GetCmsConfig200Data = {
  available_price_sources?: string[];
  configs?: GetCmsConfig200DataConfigs;
};

export type GetCmsConfig200 = {
  success?: boolean;
  data?: GetCmsConfig200Data;
};

export type PatchCmsConfigBodyUsdcBuy = {
  spread?: number;
  fee_rate?: number;
  min_fee?: number;
  min_order_amount?: number;
  max_order_amount?: number;
  source?: string;
};

export type PatchCmsConfigBodyUsdcSell = {
  spread?: number;
  fee_rate?: number;
  min_fee?: number;
  min_order_amount?: number;
  max_order_amount?: number;
  source?: string;
};

export type PatchCmsConfigBodyUsdc = {
  buy?: PatchCmsConfigBodyUsdcBuy;
  sell?: PatchCmsConfigBodyUsdcSell;
};

export type PatchCmsConfigBodyXlmBuy = {
  spread?: number;
  fee_rate?: number;
  min_fee?: number;
  min_order_amount?: number;
  max_order_amount?: number;
  source?: string;
};

export type PatchCmsConfigBodyXlmSell = {
  spread?: number;
  fee_rate?: number;
  min_fee?: number;
  min_order_amount?: number;
  max_order_amount?: number;
  source?: string;
};

export type PatchCmsConfigBodyXlm = {
  buy?: PatchCmsConfigBodyXlmBuy;
  sell?: PatchCmsConfigBodyXlmSell;
};

export type PatchCmsConfigBody = {
  usdc?: PatchCmsConfigBodyUsdc;
  xlm?: PatchCmsConfigBodyXlm;
};

export type PatchCmsConfig200DataConfigsUsdcBuy = {
  spread?: number;
  fee_rate?: number;
  min_fee?: number;
  min_order_amount?: number;
  max_order_amount?: number;
  source?: string;
};

export type PatchCmsConfig200DataConfigsUsdcSell = {
  spread?: number;
  fee_rate?: number;
  min_fee?: number;
  min_order_amount?: number;
  max_order_amount?: number;
  source?: string;
};

export type PatchCmsConfig200DataConfigsUsdc = {
  buy?: PatchCmsConfig200DataConfigsUsdcBuy;
  sell?: PatchCmsConfig200DataConfigsUsdcSell;
};

export type PatchCmsConfig200DataConfigsXlmBuy = {
  spread?: number;
  fee_rate?: number;
  min_fee?: number;
  min_order_amount?: number;
  max_order_amount?: number;
  source?: string;
};

export type PatchCmsConfig200DataConfigsXlmSell = {
  spread?: number;
  fee_rate?: number;
  min_fee?: number;
  min_order_amount?: number;
  max_order_amount?: number;
  source?: string;
};

export type PatchCmsConfig200DataConfigsXlm = {
  buy?: PatchCmsConfig200DataConfigsXlmBuy;
  sell?: PatchCmsConfig200DataConfigsXlmSell;
};

export type PatchCmsConfig200DataConfigs = {
  usdc?: PatchCmsConfig200DataConfigsUsdc;
  xlm?: PatchCmsConfig200DataConfigsXlm;
};

export type PatchCmsConfig200Data = {
  available_price_sources?: string[];
  configs?: PatchCmsConfig200DataConfigs;
};

export type PatchCmsConfig200 = {
  success?: boolean;
  data?: PatchCmsConfig200Data;
};

export type GetCmsRates200DataUsdc = {
  buy?: number;
  sell?: number;
};

export type GetCmsRates200DataXlm = {
  buy?: number;
  sell?: number;
};

export type GetCmsRates200Data = {
  usdc?: GetCmsRates200DataUsdc;
  xlm?: GetCmsRates200DataXlm;
};

export type GetCmsRates200 = {
  success?: boolean;
  data?: GetCmsRates200Data;
};

export type GetCmsAdminAudit200ItemUser = {
  name?: string;
  email?: string;
};

export type GetCmsAdminAudit200Item = {
  id?: string;
  action?: string;
  details?: string;
  createdAt?: string;
  user?: GetCmsAdminAudit200ItemUser;
};

export type PatchCmsAdminPasswordBody = {
  currentPassword: string;
  /** @minLength 8 */
  newPassword: string;
};

export type PatchCmsAdminPassword200 = {
  success?: boolean;
};

export type GetLandingP2pRates200BinanceUsdc = {
  /** @nullable */
  bestBuyPrice?: number | null;
  /** @nullable */
  bestSellPrice?: number | null;
};

export type GetLandingP2pRates200BinanceXlm = {
  /** @nullable */
  bestBuyPrice?: number | null;
  /** @nullable */
  bestSellPrice?: number | null;
};

export type GetLandingP2pRates200Binance = {
  usdc?: GetLandingP2pRates200BinanceUsdc;
  xlm?: GetLandingP2pRates200BinanceXlm;
};

export type GetLandingP2pRates200OkxUsdc = {
  /** @nullable */
  bestBuyPrice?: number | null;
  /** @nullable */
  bestSellPrice?: number | null;
};

export type GetLandingP2pRates200OkxXlm = {
  /** @nullable */
  bestBuyPrice?: number | null;
  /** @nullable */
  bestSellPrice?: number | null;
};

export type GetLandingP2pRates200Okx = {
  usdc?: GetLandingP2pRates200OkxUsdc;
  xlm?: GetLandingP2pRates200OkxXlm;
};

export type GetLandingP2pRates200BybitUsdc = {
  /** @nullable */
  bestBuyPrice?: number | null;
  /** @nullable */
  bestSellPrice?: number | null;
};

export type GetLandingP2pRates200BybitXlm = {
  /** @nullable */
  bestBuyPrice?: number | null;
  /** @nullable */
  bestSellPrice?: number | null;
};

export type GetLandingP2pRates200Bybit = {
  usdc?: GetLandingP2pRates200BybitUsdc;
  xlm?: GetLandingP2pRates200BybitXlm;
};

export type GetLandingP2pRates200OurUsdc = {
  buy?: number;
  sell?: number;
  fee_rate_buy?: number;
  fee_rate_sell?: number;
  min_fee_vnd?: number;
  created_at?: string;
};

export type GetLandingP2pRates200OurXlm = {
  buy?: number;
  sell?: number;
  fee_rate_buy?: number;
  fee_rate_sell?: number;
  min_fee_vnd?: number;
  created_at?: string;
};

export type GetLandingP2pRates200Our = {
  usdc?: GetLandingP2pRates200OurUsdc;
  xlm?: GetLandingP2pRates200OurXlm;
};

export type GetLandingP2pRates200 = {
  binance?: GetLandingP2pRates200Binance;
  okx?: GetLandingP2pRates200Okx;
  bybit?: GetLandingP2pRates200Bybit;
  our?: GetLandingP2pRates200Our;
};

export type GetLandingP2pHistoryParams = {
/**
 * @minimum 1
 * @maximum 30
 */
days?: number;
};

export type GetApiRateUsdtVnd200 = {
  created_at?: string;
  buy?: number;
  sell?: number;
  fee_rate_buy?: number;
  fee_rate_sell?: number;
  min_fee_vnd?: number;
};

export type GetApiRateXlmVnd200 = {
  created_at?: string;
  buy?: number;
  sell?: number;
  fee_rate_buy?: number;
  fee_rate_sell?: number;
  min_fee_vnd?: number;
};

export type GetConfigFeeToken200DataBuy = {
  spread?: number;
  fee_rate?: number;
  min_fee?: number;
  min_order_amount?: number;
  max_order_amount?: number;
  source?: string;
};

export type GetConfigFeeToken200DataSell = {
  spread?: number;
  fee_rate?: number;
  min_fee?: number;
  min_order_amount?: number;
  max_order_amount?: number;
  source?: string;
};

export type GetConfigFeeToken200Data = {
  token?: string;
  buy?: GetConfigFeeToken200DataBuy;
  sell?: GetConfigFeeToken200DataSell;
};

export type GetConfigFeeToken200 = {
  success?: boolean;
  data?: GetConfigFeeToken200Data;
};

export type PatchConfigBodyUSDCBuy = {
  spread?: number;
  fee_rate?: number;
  min_fee?: number;
  min_order_amount?: number;
  max_order_amount?: number;
  source?: string;
};

export type PatchConfigBodyUSDCSell = {
  spread?: number;
  fee_rate?: number;
  min_fee?: number;
  min_order_amount?: number;
  max_order_amount?: number;
  source?: string;
};

export type PatchConfigBodyXLMBuy = {
  spread?: number;
  fee_rate?: number;
  min_fee?: number;
  min_order_amount?: number;
  max_order_amount?: number;
  source?: string;
};

export type PatchConfigBodyXLMSell = {
  spread?: number;
  fee_rate?: number;
  min_fee?: number;
  min_order_amount?: number;
  max_order_amount?: number;
  source?: string;
};

export type PatchConfigBody = {
  spread_buy?: number;
  spread_sell?: number;
  fee_rate_buy?: number;
  fee_rate_sell?: number;
  usdc_spread_buy?: number;
  usdc_spread_sell?: number;
  usdc_fee_rate_buy?: number;
  usdc_fee_rate_sell?: number;
  xlm_spread_buy?: number;
  xlm_spread_sell?: number;
  xlm_fee_rate_buy?: number;
  xlm_fee_rate_sell?: number;
  usdc_min_fee?: number;
  xlm_min_fee?: number;
  USDC_buy?: PatchConfigBodyUSDCBuy;
  USDC_sell?: PatchConfigBodyUSDCSell;
  XLM_buy?: PatchConfigBodyXLMBuy;
  XLM_sell?: PatchConfigBodyXLMSell;
};

export type PostApiOrdersDepositBody = {
  /** Amount as string */
  amount: string;
  /** Chain ID (1=Stellar testnet, 0=Stellar mainnet) */
  chain_id: number;
  /** Token issuer (required for USDC, empty for XLM native) */
  token_address?: string;
  /** Token code (e.g. USDC, XLM) */
  asset_code: string;
  /** User's wallet to receive tokens */
  recipient: string;
  /** Webhook URL for order state changes */
  callback: string;
  /** Optional client user ID */
  user_id?: string;
};

export type PostApiOrdersDeposit200Data = { [key: string]: unknown };

export type PostApiOrdersDeposit200 = {
  success?: boolean;
  data?: PostApiOrdersDeposit200Data;
};

export type PostApiOrdersWithdrawalBodyPaymentInfo = {
  /** Bank name (MBBank, Techcombank, etc.) */
  bank_id: string;
  /** Account holder name (no accents) */
  full_name: string;
  account_type: number;
  account_number: string;
};

export type PostApiOrdersWithdrawalBody = {
  amount: string;
  chain_id: number;
  /** Token issuer (required for USDC, empty for XLM native) */
  token_address?: string;
  /** Token code (e.g. USDC, XLM) */
  asset_code: string;
  callback: string;
  user_id?: string;
  payment_info: PostApiOrdersWithdrawalBodyPaymentInfo;
};

export type PostApiOrdersWithdrawal200Data = { [key: string]: unknown };

export type PostApiOrdersWithdrawal200 = {
  success?: boolean;
  data?: PostApiOrdersWithdrawal200Data;
};

export type GetApiOrdersId200Data = { [key: string]: unknown };

export type GetApiOrdersId200 = {
  success?: boolean;
  data?: GetApiOrdersId200Data;
};

export type GetApiOrdersId404Error = {
  code?: string;
  message?: string;
  retriable?: boolean;
  trace_id?: string;
};

export type GetApiOrdersId404 = {
  success?: boolean;
  error?: GetApiOrdersId404Error;
};

export type PostApiOrdersIdCancelBody = {
  /** Optional cancellation reason */
  reason?: string;
};

export type PostApiOrdersIdCancel200Data = { [key: string]: unknown };

export type PostApiOrdersIdCancel200 = {
  success?: boolean;
  data?: PostApiOrdersIdCancel200Data;
};

export type PostApiOrdersIdCancel404Error = {
  code?: string;
  message?: string;
  retriable?: boolean;
  trace_id?: string;
};

export type PostApiOrdersIdCancel404 = {
  success?: boolean;
  error?: PostApiOrdersIdCancel404Error;
};

export type PostApiOrdersIdCancel409Error = {
  code?: string;
  message?: string;
  retriable?: boolean;
  trace_id?: string;
};

export type PostApiOrdersIdCancel409 = {
  success?: boolean;
  error?: PostApiOrdersIdCancel409Error;
};

export type PostApiWebhooksSepayBodyTransferType = typeof PostApiWebhooksSepayBodyTransferType[keyof typeof PostApiWebhooksSepayBodyTransferType];


export const PostApiWebhooksSepayBodyTransferType = {
  in: 'in',
  out: 'out',
} as const;

export type PostApiWebhooksSepayBody = {
  /** Transaction ID on SePay */
  id?: number;
  /** Bank brand name */
  gateway?: string;
  transactionDate?: string;
  accountNumber?: string;
  /**
     * Payment code detected by SePay
     * @nullable
     */
  code?: string | null;
  /** Transfer description */
  content?: string;
  transferType?: PostApiWebhooksSepayBodyTransferType;
  /** Amount in VND */
  transferAmount?: number;
  accumulated?: number;
  /** @nullable */
  subAccount?: string | null;
  referenceCode?: string;
  description?: string;
};

export type PostApiWebhooksSepay200 = {
  success?: boolean;
};

export type PostApiWebhooksStellarIncomingBody = {
  txHash: string;
  from?: string;
  to?: string;
  amount: string;
  asset: string;
  tokenIssuer?: string;
  timestamp?: string;
  walletLabel?: string;
  memo?: string;
};

export type PostApiWebhooksStellarIncoming200 = {
  success?: boolean;
};

export type PostApiWebhooksStellarIncoming400Error = { [key: string]: unknown };

export type PostApiWebhooksStellarIncoming400 = {
  success?: boolean;
  error?: PostApiWebhooksStellarIncoming400Error;
};

