/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Payment Service API
 * Price engine, fee management and SePay payment integration
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetApiOrdersId200,
  GetApiRateUsdtVnd200,
  GetApiRateXlmVnd200,
  GetCmsAdminAudit200Item,
  GetCmsConfig200,
  GetCmsRates200,
  GetConfigFeeToken200,
  GetLandingP2pHistoryParams,
  GetLandingP2pRates200,
  GetStatsParams,
  PatchCallbackSecret200,
  PatchCallbackSecretBody,
  PatchCmsAdminPassword200,
  PatchCmsAdminPasswordBody,
  PatchCmsConfig200,
  PatchCmsConfigBody,
  PatchConfigBody,
  PostApiOrdersDeposit200,
  PostApiOrdersDepositBody,
  PostApiOrdersIdCancel200,
  PostApiOrdersIdCancelBody,
  PostApiOrdersWithdrawal200,
  PostApiOrdersWithdrawalBody,
  PostApiWebhooksSepay200,
  PostApiWebhooksSepayBody,
  PostApiWebhooksStellarIncoming200,
  PostApiWebhooksStellarIncomingBody,
  PostBypassPaymentBody,
  PostBypassSellPaymentBody,
  PostCmsAdmins201,
  PostCmsAdminsBody,
  PostCmsLogin200,
  PostCmsLoginBody,
  PostLoginBody
} from './api.schemas';




  export const getPaymentServiceAPI = (axiosInstance: AxiosInstance = axios) => {
const getOpenapiJson = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/openapi.json`,options
    );
  }

const getHealth = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/health`,options
    );
  }

/**
 * @summary Admin login (JWT)
 */
const postLogin = (
    postLoginBody: PostLoginBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/login`,
      postLoginBody,options
    );
  }

/**
 * @summary Get BI stats (admin)
 */
const getStats = (
    params?: GetStatsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/stats`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Rotate callback signature secret
 */
const patchCallbackSecret = (
    patchCallbackSecretBody: PatchCallbackSecretBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PatchCallbackSecret200>> => {
    return axiosInstance.patch(
      `/callback-secret`,
      patchCallbackSecretBody,options
    );
  }

/**
 * @summary Bypass payment for buy order (admin key)
 */
const postBypassPayment = (
    postBypassPaymentBody: PostBypassPaymentBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/bypass-payment`,
      postBypassPaymentBody,options
    );
  }

/**
 * @summary Bypass payment for sell order (admin key)
 */
const postBypassSellPayment = (
    postBypassSellPaymentBody: PostBypassSellPaymentBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/bypass-sell-payment`,
      postBypassSellPaymentBody,options
    );
  }

/**
 * @summary CMS admin login (JWT)
 */
const postCmsLogin = (
    postCmsLoginBody: PostCmsLoginBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostCmsLogin200>> => {
    return axiosInstance.post(
      `/cms/login`,
      postCmsLoginBody,options
    );
  }

/**
 * @summary Create a new admin account
 */
const postCmsAdmins = (
    postCmsAdminsBody: PostCmsAdminsBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostCmsAdmins201>> => {
    return axiosInstance.post(
      `/cms/admins`,
      postCmsAdminsBody,options
    );
  }

/**
 * @summary Get per-token spreads and fee rates (creates defaults if missing)
 */
const getCmsConfig = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetCmsConfig200>> => {
    return axiosInstance.get(
      `/cms/config`,options
    );
  }

/**
 * @summary Update per-token spreads and fee rates
 */
const patchCmsConfig = (
    patchCmsConfigBody: PatchCmsConfigBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PatchCmsConfig200>> => {
    return axiosInstance.patch(
      `/cms/config`,
      patchCmsConfigBody,options
    );
  }

/**
 * @summary Get buy and sell rates for all tokens (USDC, XLM)
 */
const getCmsRates = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetCmsRates200>> => {
    return axiosInstance.get(
      `/cms/rates`,options
    );
  }

/**
 * @summary Get last 50 fee config audit log entries
 */
const getCmsAdminAudit = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetCmsAdminAudit200Item[]>> => {
    return axiosInstance.get(
      `/cms/admin/audit`,options
    );
  }

/**
 * @summary Get all buy orders
 */
const getCmsOrdersBuy = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/cms/orders/buy`,options
    );
  }

/**
 * @summary Get all sell orders
 */
const getCmsOrdersSell = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/cms/orders/sell`,options
    );
  }

/**
 * @summary Change admin password
 */
const patchCmsAdminPassword = (
    patchCmsAdminPasswordBody: PatchCmsAdminPasswordBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PatchCmsAdminPassword200>> => {
    return axiosInstance.patch(
      `/cms/admin/password`,
      patchCmsAdminPasswordBody,options
    );
  }

/**
 * @summary Get all P2P rates (Binance, OKX, Bybit) and our price
 */
const getLandingP2pRates = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetLandingP2pRates200>> => {
    return axiosInstance.get(
      `/landing/p2p-rates`,options
    );
  }

/**
 * @summary Get price history for all exchanges (Binance, OKX, Bybit, Our)
 */
const getLandingP2pHistory = (
    params?: GetLandingP2pHistoryParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/landing/p2p-history`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Get live USDC/VND buy and sell rates (price per 1 USDC)
 */
const getApiRateUsdtVnd = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetApiRateUsdtVnd200>> => {
    return axiosInstance.get(
      `/api/rate/usdt_vnd`,options
    );
  }

/**
 * @summary Get live XLM/VND buy and sell rates (price per 1 XLM)
 */
const getApiRateXlmVnd = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetApiRateXlmVnd200>> => {
    return axiosInstance.get(
      `/api/rate/xlm_vnd`,options
    );
  }

/**
 * @summary Get current spreads and fee rates (global + token-specific)
 */
const getConfigFees = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/config/fees`,options
    );
  }

/**
 * @summary Get all fee config for a token
 */
const getConfigFeeToken = (
    token: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetConfigFeeToken200>> => {
    return axiosInstance.get(
      `/config/fee/${token}`,options
    );
  }

/**
 * @summary Update spreads and fee rates (admin, global + token-specific)
 */
const patchConfig = (
    patchConfigBody: PatchConfigBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.patch(
      `/config/`,
      patchConfigBody,options
    );
  }

/**
 * @summary Create a deposit order (buy USDC/XLM) — returns SePay checkout session
 */
const postApiOrdersDeposit = (
    postApiOrdersDepositBody: PostApiOrdersDepositBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostApiOrdersDeposit200>> => {
    return axiosInstance.post(
      `/api/orders/deposit`,
      postApiOrdersDepositBody,options
    );
  }

/**
 * @summary Create a withdrawal order (sell USDC/XLM) — stub, logic incomplete
 */
const postApiOrdersWithdrawal = (
    postApiOrdersWithdrawalBody: PostApiOrdersWithdrawalBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostApiOrdersWithdrawal200>> => {
    return axiosInstance.post(
      `/api/orders/withdrawal`,
      postApiOrdersWithdrawalBody,options
    );
  }

/**
 * @summary Get order status by ID
 */
const getApiOrdersId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetApiOrdersId200>> => {
    return axiosInstance.get(
      `/api/orders/${id}`,options
    );
  }

/**
 * @summary Cancel an order by ID
 */
const postApiOrdersIdCancel = (
    id: string,
    postApiOrdersIdCancelBody: PostApiOrdersIdCancelBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostApiOrdersIdCancel200>> => {
    return axiosInstance.post(
      `/api/orders/${id}/cancel`,
      postApiOrdersIdCancelBody,options
    );
  }

const getApiOrdersIdCancel = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/orders/${id}/cancel`,options
    );
  }

const getApiOrdersIdSuccess = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/orders/${id}/success`,options
    );
  }

const getApiOrdersIdError = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/orders/${id}/error`,options
    );
  }

/**
 * @summary SePay bank transaction webhook — receives deposit notifications
 */
const postApiWebhooksSepay = (
    postApiWebhooksSepayBody: PostApiWebhooksSepayBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostApiWebhooksSepay200>> => {
    return axiosInstance.post(
      `/api/webhooks/sepay`,
      postApiWebhooksSepayBody,options
    );
  }

/**
 * @summary Stellar incoming webhook — fallback when Kafka unavailable
 */
const postApiWebhooksStellarIncoming = (
    postApiWebhooksStellarIncomingBody: PostApiWebhooksStellarIncomingBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostApiWebhooksStellarIncoming200>> => {
    return axiosInstance.post(
      `/api/webhooks/stellar-incoming`,
      postApiWebhooksStellarIncomingBody,options
    );
  }

return {getOpenapiJson,getHealth,postLogin,getStats,patchCallbackSecret,postBypassPayment,postBypassSellPayment,postCmsLogin,postCmsAdmins,getCmsConfig,patchCmsConfig,getCmsRates,getCmsAdminAudit,getCmsOrdersBuy,getCmsOrdersSell,patchCmsAdminPassword,getLandingP2pRates,getLandingP2pHistory,getApiRateUsdtVnd,getApiRateXlmVnd,getConfigFees,getConfigFeeToken,patchConfig,postApiOrdersDeposit,postApiOrdersWithdrawal,getApiOrdersId,postApiOrdersIdCancel,getApiOrdersIdCancel,getApiOrdersIdSuccess,getApiOrdersIdError,postApiWebhooksSepay,postApiWebhooksStellarIncoming}};
export type GetOpenapiJsonResult = AxiosResponse<void>
export type GetHealthResult = AxiosResponse<void>
export type PostLoginResult = AxiosResponse<void>
export type GetStatsResult = AxiosResponse<void>
export type PatchCallbackSecretResult = AxiosResponse<PatchCallbackSecret200>
export type PostBypassPaymentResult = AxiosResponse<void>
export type PostBypassSellPaymentResult = AxiosResponse<void>
export type PostCmsLoginResult = AxiosResponse<PostCmsLogin200>
export type PostCmsAdminsResult = AxiosResponse<PostCmsAdmins201>
export type GetCmsConfigResult = AxiosResponse<GetCmsConfig200>
export type PatchCmsConfigResult = AxiosResponse<PatchCmsConfig200>
export type GetCmsRatesResult = AxiosResponse<GetCmsRates200>
export type GetCmsAdminAuditResult = AxiosResponse<GetCmsAdminAudit200Item[]>
export type GetCmsOrdersBuyResult = AxiosResponse<void>
export type GetCmsOrdersSellResult = AxiosResponse<void>
export type PatchCmsAdminPasswordResult = AxiosResponse<PatchCmsAdminPassword200>
export type GetLandingP2pRatesResult = AxiosResponse<GetLandingP2pRates200>
export type GetLandingP2pHistoryResult = AxiosResponse<void>
export type GetApiRateUsdtVndResult = AxiosResponse<GetApiRateUsdtVnd200>
export type GetApiRateXlmVndResult = AxiosResponse<GetApiRateXlmVnd200>
export type GetConfigFeesResult = AxiosResponse<void>
export type GetConfigFeeTokenResult = AxiosResponse<GetConfigFeeToken200>
export type PatchConfigResult = AxiosResponse<void>
export type PostApiOrdersDepositResult = AxiosResponse<PostApiOrdersDeposit200>
export type PostApiOrdersWithdrawalResult = AxiosResponse<PostApiOrdersWithdrawal200>
export type GetApiOrdersIdResult = AxiosResponse<GetApiOrdersId200>
export type PostApiOrdersIdCancelResult = AxiosResponse<PostApiOrdersIdCancel200>
export type GetApiOrdersIdCancelResult = AxiosResponse<void>
export type GetApiOrdersIdSuccessResult = AxiosResponse<void>
export type GetApiOrdersIdErrorResult = AxiosResponse<void>
export type PostApiWebhooksSepayResult = AxiosResponse<PostApiWebhooksSepay200>
export type PostApiWebhooksStellarIncomingResult = AxiosResponse<PostApiWebhooksStellarIncoming200>
